### Change the port number based on the port number generate by AWS API Gateway Emulartor. The API Gateway Endpoint Emulator will run on different endpoint when we restart the service.  Todo: Still need to find the way to keep the port number same.

@port = 49326
@baseUrl = http://localhost:{{port}}

### Get all values
GET {{baseUrl}}/api/values
Accept: application/json

###

### Get value by id
GET {{baseUrl}}/api/values/5
Accept: application/json

###

### Create a new value
POST {{baseUrl}}/api/values
Content-Type: application/json

"value3"

###

### Update a value
PUT {{baseUrl}}/api/values/5
Content-Type: application/json

"updated value"

###

### Delete a value
DELETE {{baseUrl}}/api/values/5
Accept: application/json
