@SampleWebAPI_HostAddress = https://localhost:5050

### Sample TEST API
GET {{ SampleWebAPI_HostAddress}}/test/
Accept: application/json

### Get Weather Forecast with Redis Enable
GET {{SampleWebAPI_HostAddress}}/weatherforecast-redis/
Accept: application/json
